name: lrl_shopping
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Required for initializing Firebase in Flutter
  firebase_core: ^3.11.0
  # Helps track and report app crashes in real-time
  firebase_crashlytics: ^4.3.2

  # for fonts
  google_fonts: ^6.2.1
  # for localization
  easy_localization: ^3.0.7+1
  # Functional programming things
  dartz: ^0.10.1
  # for state management
  flutter_bloc: ^9.0.0
  # Value equality
  equatable: ^2.0.7
  # Remote API
  dio: ^5.8.0+1
  pretty_dio_logger: ^1.4.0
  get_it: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # Generates Android & iOS launcher icons
  flutter_launcher_icons: ^0.13.1
  # for different flavor integration
  flutter_flavorizr: ^2.2.3

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/language/

    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

flavorizr:
  ide: "vscode"
  flavors:
    development:
      app:
        name: "Shopping dev"

      android:
        applicationId: "com.majharulDev.shoppingDev"
      ios:
        bundleId: "com.majharulDev.shoppingDev"
      macos:
        bundleId: "com.majharulDev.shoppingDev"
      entrypoint: "lib/app/env/main_development.dart"
    production:
      app:
        name: "Shopping prod"

      android:
        applicationId: "com.majharulDev.shoppingProd"
      ios:
        bundleId: "com.majharulDev.shoppingProd"
      macos:
        bundleId: "com.majharulDev.shoppingProd"
      entrypoint: "lib/app/env/main_production.dart"